### ISSUE TITLE
IndentationError test_trainmodel.py <Muskan branch>

### ISSUE THREAD

**Issue by ucalyptus** [ucalyptus/DesignLabProject#5]
**Traceback**
Traceback (most recent call last):
  File "/home/ucalyptus/anaconda3/envs/designlab/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ucalyptus/anaconda3/envs/designlab/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ucalyptus/anaconda3/envs/designlab/lib/python3.6/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/home/ucalyptus/anaconda3/envs/designlab/lib/python3.6/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/home/ucalyptus/anaconda3/envs/designlab/lib/python3.6/unittest/main.py", line 141, in parseArgs
    self.createTests()
  File "/home/ucalyptus/anaconda3/envs/designlab/lib/python3.6/unittest/main.py", line 148, in createTests
    self.module)
  File "/home/ucalyptus/anaconda3/envs/designlab/lib/python3.6/unittest/loader.py", line 219, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/ucalyptus/anaconda3/envs/designlab/lib/python3.6/unittest/loader.py", line 219, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/ucalyptus/anaconda3/envs/designlab/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/ucalyptus/DesignLabProject/tests/test_trainmodel.py", line 17
    def test_validAgeRange(self):
    ^
IndentationError: unexpected indent

**Steps to reproduce this issue**
- `cd tests`
- `sh runtest.sh`

**Comment by muskan0508** [comment]
Issue resolved
